### ISSUE TITLE
Provide existing certificates to Docker production deployment 

### ISSUE THREAD

**Issue by vemonet** [solid/node-solid-server#1469]
I am working on getting Solid working with https://github.com/nginx-proxy/nginx-proxy

The certs are generated on my server at `/data/mycerts/solid.myhostname.org` (a `cert.pem` and a `key.pem`)

From there it should be just a matter of finding the right volumes to share the generated let's encrypt certs between the Solid-server container and my machine:

Here an example docker-compose, I try to use the `solid start--ssl-key` and `--ssl-cert` arguments as explained in the readme. The Dockerfile also use the npm package `solid start` as entrypoint, but it fails when we run it `solid-server | error: unknown option '--ssl-cert'` 

```yaml
version: "3"
services:

  solid:
    image: nodesolidserver/node-solid-server:latest
    container_name: solid-server
    ports:
      - 8443:8443
    command: "--ssl-cert /data/certs/cert.pem --ssl-key /data/certs/key.pem"
    environment: 
      - VIRTUAL_HOST=solid.myhostname.org
      - LETSENCRYPT_HOST=solid.myhostname.org
      - VIRTUAL_PORT=8443
    volumes: 
      - /data/certs/solid.myhostname.org:/data/certs
    restart: unless-stopped
```

The **documentation is not clear whereas where the certs and key should be put for the Solid node server**

Especially when it comes to using "standard" containers such as docker, there should be some documentation simply explaining where the certs need to be shared with the `Solid node` container (and it should be doable directly in the `docker run` command, we should not need extra manual commands)
