### ISSUE TITLE
Error fetching openid configuration: 502 Bad Gateway

### ISSUE THREAD

**Issue by pheyvaer** [solid/node-solid-server#1504]
Hi,

I get an error when running the server behind NGINX. NSS and NGINX are running on two different machines.

I do `solid start` with the following config:
```
{
  "root": "/users/pheyvaer/nss/data",
  "port": "8443",
  "serverUri": "https://dev.inclusie-in-4d.ilabt.imec.be",
  "webid": true,
  "mount": "",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "",
  "sslKey": "privkey.pem",
  "sslCert": "fullchain.pem",
  "multiuser": true,
  "enforceToc": false,
  "disablePasswordChecks": false,
  "supportEmail": "pieter.heyvaert@ugent.be",
  "server": {
    "name": "Inclusie in 4D",
    "description": "",
    "logo": ""
  }
}
```

I get this error
```
Error registering a new client:  Error: Error fetching openid configuration: 502 Bad Gateway
    at /users/pheyvaer/.nvm/versions/node/v12.19.0/lib/node_modules/solid-server/node_modules/@solid/oidc-rp/src/onHttpError.js:32:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://dev.inclusie-in-4d.ilabt.imec.be/.well-known/openid-configuration',
      status: 502,
      statusText: 'Bad Gateway',
      headers: [Headers],
      counter: 0
    }
  },
  statusCode: 502
}
```

A wildcard certificate is implemented for the `*.dev.inclusie-in-4d.ilabt.imec.be`. I'm also wondering where the `.well-known/openid-configuration` is coming from. Is it something that is provided by NSS?

**Comment by bourgeoa** [comment]
Can you try to start with DEBUG="solid:*"

**Comment by michielbdejong** [comment]
what do you see when you visit https://dev.inclusie-in-4d.ilabt.imec.be/.well-known/openid-configuration from the box that runs NSS?

I see a 502 when I visit it from the public internet.

The cert is valid though, look: https://dev.inclusie-in-4d.ilabt.imec.be/.well-known/openid-configuration

This looks like an error that's coming from Nginx. Have a look at what Nginx would see when it proxies this request to https://nss-box-local-ip-addr:8443/.well-known/openid-configuration

Yes, this file is provided by NSS, it should look something like https://solidcommunity.net/.well-known/openid-configuration
And it's also consumed by NSS (which admittedly is a bit weird, it should not go via the public internet when dereferencing files it hosts itself, but that's due to separation between IDP code and LDP storage code)

**Comment by pheyvaer** [comment]
Using curl I get 
```
curl: (51) SSL: no alternative certificate subject name matches target host name '192.168.49.1'
```

**Comment by michielbdejong** [comment]
Try `curl -k` to ignore the SSL error.
Also make sure to run node-solid-server with the `NODE_TLS_REJECT_UNAUTHORIZED=0` to work around your self-signed cert. An easy way to do this is to use `./bin/solid-test start` instead of `./bin/solid start`.

**Comment by pheyvaer** [comment]
But it's not a self-signed cert though. We use Let's Encrypt to have a wildcard cert for the whole domain.

**Comment by vemonet** [comment]
We are facing similar issues with deploying Solid behind a Nginx proxy with Letsencrypt companion (cf. https://github.com/nginx-proxy) 

The exact same setup was perfectly working a few days/weeks ago. And we did not do any change apart from restarting the docker-compose

I am getting the same issue as @pheyvaer :

```
solid-server | 2020-11-10T15:04:30.763Z solid:authentication Provider keys loaded from config
solid-server | 2020-11-10T15:04:30.781Z solid:authentication Provider keychain initialized
solid-server | 2020-11-10T15:04:30.782Z solid:authentication Not sleeping before client registration...
solid-server | 2020-11-10T15:04:30.783Z solid:authentication Client not present for issuer https://solid.137.120.31.102.nip.io, initializing new client
solid-server | 2020-11-10T15:04:30.783Z solid:authentication Registering new client for issuer  https://solid.137.120.31.102.nip.io
solid-server | 2020-11-10T15:04:30.817Z solid:authentication Error registering a new client:  { FetchError: request to https://solid.137.120.31.102.nip.io/.well-known/openid-configuration failed, reason: self signed certificate
solid-server |     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/solid-server/node_modules/node-fetch/lib/index.js:1455:11)
solid-server |     at ClientRequest.emit (events.js:198:13)
solid-server |     at TLSSocket.socketErrorListener (_http_client.js:401:9)
solid-server |     at TLSSocket.emit (events.js:198:13)
solid-server |     at emitErrorNT (internal/streams/destroy.js:91:8)
solid-server |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
solid-server |     at process._tickCallback (internal/process/next_tick.js:63:19)
solid-server |   message:
solid-server |    'request to https://solid.137.120.31.102.nip.io/.well-known/openid-configuration failed, reason: self signed certificate',
solid-server |   type: 'system',
solid-server |   errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
solid-server |   code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
solid-server | 2020-11-10T15:04:30.819Z solid:authentication Error initializing local RP client:  { FetchError: request to https://solid.137.120.31.102.nip.io/.well-known/openid-configuration failed, reason: self signed certificate
solid-server |     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/solid-server/node_modules/node-fetch/lib/index.js:1455:11)
solid-server |     at ClientRequest.emit (events.js:198:13)
solid-server |     at TLSSocket.socketErrorListener (_http_client.js:401:9)
solid-server |     at TLSSocket.emit (events.js:198:13)
solid-server |     at emitErrorNT (internal/streams/destroy.js:91:8)
solid-server |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
solid-server |     at process._tickCallback (internal/process/next_tick.js:63:19)
solid-server |   message:
solid-server |    'request to https://solid.137.120.31.102.nip.io/.well-known/openid-configuration failed, reason: self signed certificate',
solid-server |   type: 'system',
solid-server |   errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
solid-server |   code: 'DEPTH_ZERO_SELF_SIGNED_CERT' }
```

**Those are not self-signed certificates**. Those are certificates that work for all of others applications run on our server (a few dozen), and who were working a few weeks ago

Here is the `docker-compose.yml` we use:

```yml
version: "3"
services:
  solid:
    image: nodesolidserver/node-solid-server:latest
    container_name: solid-server
    restart: unless-stopped
    ports:
      - 8443:8443
    environment: 
      - "SOLID_SERVER_URI=https://solid.137.120.31.102.nip.io"
      - "SOLID_SSL_KEY=/opt/solid/certs/solid.137.120.31.102.nip.io/key.pem"
      - "SOLID_SSL_CERT=/opt/solid/certs/solid.137.120.31.102.nip.io/fullchain.pem"
      - "SOLID_MULTIUSER=true"
      - "SOLID_SERVER_NAME=Solid server at IDS"
      - "SOLID_SERVER_DESCRIPTION=Solid server hosted at the Institute of Data Science at Maastricht University"
      - "VIRTUAL_HOST=solid.137.120.31.102.nip.io,*.solid.137.120.31.102.nip.io"
      - "LETSENCRYPT_HOST=solid.137.120.31.102.nip.io,vemonet.solid.137.120.31.102.nip.io"
      - "VIRTUAL_PORT=8443"
      - "VIRTUAL_PROTO=https"
    volumes: 
      - /data/certs:/opt/solid/certs
      - /data/solid/data:/opt/solid/data
      - /data/solid/.db:/opt/solid/.db
      - /data/solid/config:/opt/solid/config
```

> But it's not a self-signed cert though. We use Let's Encrypt to have a wildcard cert for the whole domain.

@pheyvaer Last time I checked LetsEncrypt could not handle wildcard (according to discussion in issues, only `VIRTUAL_HOST` would handle wildcarded subdomains). Did it work for you to provide something like `*.solid.137.120.31.102.nip.io` for the `LETSENCRYPT_HOST`
