### ISSUE TITLE
Consider adding a snapcraft.yaml file

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#482]
[Snapcraft](http://snapcraft.io/) allows you to package any app for every Linux desktop, server, cloud or device, and deliver updates directly

This is a request resulting form a conversation with @metcors : 

https://gitter.im/solid/chat?at=586b7af6c02c1a3959e04662

An example of deploying a nodejs server snap is here:

https://github.com/snapcore/snapcraft/tree/master/tour/10-SNAPS/02-service-confined

```yaml
name: hello-world-service
version: 0.1
summary: A hello world style nodejs webserver app
description: 
  This example demonstrates how to have nodejs webserver.
  This is part of the snapcraft tour at http://snapcraft.io/create/
confinement: strict

apps:
  hello-service:
    command: hello-world
    daemon: simple
    plugs: [network-bind]

parts:
  hello:
    plugin: nodejs
    source: .
```

There is also a [tutorial](http://snapcraft.io/create/) for creating yaml files.

However, one outstanding question I have is what values to use in the config.json.
